configurations:
- sources:
    - Sources/GlycoKit
  templates:
    - Sourcery/Languages.stencil
  output: Languages.md
- sources:
    - Sources/GlycoKit
  templates:
    - Sourcery/Codable.stencil
  output: Sources/GlycoKit/Generated
