configurations:
- sources:
    - Sources/GlycoKit
  templates:
    - Sourcery/Languages.stencil
  output: Languages.md
- sources:
    - Sources/GlycoKit
  templates:
    - Sourcery/Codable.stencil
  output: Sources/GlycoKit
- sources:
    - Sources/GlycoKit
  templates:
    - Sourcery/Summary (Text).stencil
  output: ../Text/Language Summary.tex
