default:
  image: swift:5.5.1-focal
  cache:
    key: "shared cache"
    paths:
      - "Glyco/.build"

stages:
  - build
  - test

build: &build
  stage: build
  script:
    - cd Glyco
    - swift build -c release -Xswiftc -static-executable
    - cd ..
    - mkdir Glyco_release_Ubuntu20.04
    - cp Glyco/.build/release/Glyco Glyco_release_Ubuntu20.04/Glyco
  artifacts:
    paths:
      - Glyco_release_Ubuntu20.04

test: &test
  stage: test
  script:
    - cd Glyco
    - swift test
