default:
  image: swift:5.5
  cache:
    key: "shared cache"
    paths:
      - "Glyco/.build"

stages:
  - build
  - test

build: &build
  stage: build
  script:
    - cd Glyco
    - swift build
  artifacts:
    paths:
      - "Glyco/.build/debug/Glyco"

test: &test
  stage: test
  script:
    - cd Glyco
    - swift test
