stages:
  - build
  - test
  - text

build: &build
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - |-
       KANIKOPROXYBUILDARGS=""
       KANIKOCFG="\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}"
       if [ "x${http_proxy}" != "x" -o "x${https_proxy}" != "x" ]; then
         KANIKOCFG="${KANIKOCFG}, \"proxies\": { \"default\": { \"httpProxy\": \"${http_proxy}\", \"httpsProxy\": \"${https_proxy}\", \"noProxy\": \"${no_proxy}\"}}"
         KANIKOPROXYBUILDARGS="--build-arg http_proxy=${http_proxy} --build-arg https_proxy=${https_proxy} --build-arg no_proxy=${no_proxy}"
       fi
       KANIKOCFG="{ ${KANIKOCFG} }"
       echo "${KANIKOCFG}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --cache=true
      --cache-dir=/cache
      --cache-ttl=4368h
      --context "${CI_PROJECT_DIR}/Glyco"
      --dockerfile "${CI_PROJECT_DIR}/Glyco/Dockerfile"
      "${KANIKOPROXYBUILDARGS}"
      --destination "${CI_REGISTRY_IMAGE}/glyco:${CI_COMMIT_SHORT_SHA}"
  cache:
    key: "Kaniko cache"
    paths:
      - "/cache"

test: &test
  stage: test
  needs: []
  image: swift:5.6.1-focal
  script:
    - cd Glyco
    - swift test
  cache:
    key: "Glyco build cache"
    paths:
      - "Glyco/.build"

text: &text
  stage: text
  needs: []
  image: texlive/texlive:latest
  script:
      - cd Text
      - latexmk -shell-escape -pdf -pdflatex main.tex
  artifacts:
    paths:
      - Text/main.pdf
  cache:
    key: "Intermediate LaTeX files"
    paths:
      - "Text"
