default:
  image: swift:5.6.1-focal
  cache:
    key: "shared cache"
    paths:
      - "Glyco/.build"

stages:
  - build
  - test

build: &build
  stage: build
  script:
    - cd Glyco
    - swift build -c release -Xswiftc -static-executable
    - cp -a $(swift build -c release --show-bin-path) ../Glyco_release_Ubuntu20.04
    - cd ..
  artifacts:
    paths:
      - Glyco_release_Ubuntu20.04

test: &test
  stage: test
  needs: [build]
  script:
    - cd Glyco
    - swift test
