default:
  image: swift:5.5.3-focal
  cache:
    key: "shared cache"
    paths:
      - "Glyco/.build"

stages:
  - build
  - test
  - text

build: &build
  stage: build
  script:
    - cd Glyco
    - swift build -c release -Xswiftc -static-executable
    - cd ..
    - mkdir Glyco_release_Ubuntu20.04
    - cp Glyco/.build/release/Glyco Glyco_release_Ubuntu20.04/Glyco
  artifacts:
    paths:
      - Glyco_release_Ubuntu20.04

text:
  stage: text
  needs: []
  image: texlive/texlive:latest
  script:
      - cd Text
      - latexmk -pdf -pdflatex main.tex
  artifacts:
    paths:
      - Text/main.pdf

test: &test
  stage: test
  needs: [build]
  script:
    - cd Glyco
    - swift test
