default:
  image: swift:5.5.1-focal
  cache:
    key: "shared cache"
    paths:
      - "Glyco/.build"

stages:
  - build
  - test

build: &build
  stage: build
  script:
    - cd Glyco
    - swift build -c release
  artifacts:
    paths:
      - Glyco/.build/release

test: &test
  stage: test
  script:
    - cd Glyco
    - swift test
